### ISSUE TITLE
Make a temporary logo

### ISSUE THREAD

**Issue by Potherca** [pdsinterop/project-admin#11]
As discussed during the 2020-06-15 weekly meeting, as part of the ongoing effort to create a brand identity for PDS Interop, a logo is needed.

**Comment by Potherca** [comment]
Today I was explaining to someone what Solid is, and discussing PDS Interop and our Solid-Nextcloud project.

I made a drawing (on paper) that looked more or less like this:

![canvas](https://user-images.githubusercontent.com/195757/85756273-f2d9b300-b70e-11ea-9fc9-cc006443f9f4.png)

Somehow this struct me as something that might be nice to use as a logo, so I gave it a go...

My attempts look like this:

1. ![pdsinterop-logo](https://user-images.githubusercontent.com/195757/85756772-65e32980-b70f-11ea-92ef-34404b68fd1e.png)
2. ![pdsinterop-logo2](https://user-images.githubusercontent.com/195757/85756776-667bc000-b70f-11ea-8383-7a935019b05c.png)
3. ![pdsinterop-logo3](https://user-images.githubusercontent.com/195757/85756778-67145680-b70f-11ea-8893-c2db96002d76.png)
4. ![pdsinterop-logo4](https://user-images.githubusercontent.com/195757/85756781-67145680-b70f-11ea-9dc8-b60d50e20836.png)

What do you think? Useable?

**Comment by ylebre** [comment]
I like the shape and colors. Not crazy about the gradients. Would it be possible to do the second version with solid lines between all the colors and see how that looks? I guess that would be like v1 but with thicker lines.

**Comment by Potherca** [comment]
@ylebre That's the great thing about using SVG, it's no work at all 😁 

Did you mean something like this?

![image](https://user-images.githubusercontent.com/195757/85775520-25d87280-b720-11ea-94af-6e04f928c91c.png)

<sup>(SVG code for reference)</sup>
```
<svg xmlns="http://www.w3.org/2000/svg" stroke="#000" stroke-width="0" viewBox="-5 -5 110 110"><circle cx="50" cy="50" r="51" fill="#7C4DFF" stroke="none"/><circle cx="50" cy="50" r="34" fill="#F2E205" stroke="none"/><path fill="#FFF" stroke-width="2" d="M0 50h15a38.5 38.5 0 0029.5 34.75V69A20 20 0 0150 29.75 20 20 0 0155.5 69v15.75A38.5 38.5 0 0085 50h15A1 1 0 010 50z"/></svg>
```

**Comment by michielbdejong** [comment]
\o/

**Comment by poef** [comment]
looking good, small nitpicks:

- gradients in logo's are usually discouraged because they don't transfer well to some media (flags, side of a van, etc.) Also, flat is in right now.
- the width of the 'neck' is a bit too small compared to the 'arms', and the width of the circles

**Comment by Potherca** [comment]
I've updated my preview comment with the latest version. :+1:

**Comment by ylebre** [comment]
Works for me!

**Comment by Potherca** [comment]
As requested during today's weekly: a monochrome version (the blue background has been added for clarity, will be removed in final draft).

@poef what do you think? Is the "gap" good or does it need to be wider?

## Monochrome version

| Size (in pixels) | Image |
| ---------------- | ----- |
| 16x16 | <img src="https://gist.githubusercontent.com/Potherca/139c4ba16cad5961d3468b8e3db261de/raw/pdsinterop-logo-monochrome.svg" width="16" /> |
| 32x32 | <img src="https://gist.githubusercontent.com/Potherca/139c4ba16cad5961d3468b8e3db261de/raw/pdsinterop-logo-monochrome.svg" width="32" /> |
| 64x64 | <img src="https://gist.githubusercontent.com/Potherca/139c4ba16cad5961d3468b8e3db261de/raw/pdsinterop-logo-monochrome.svg" width="64" /> |
| 128x128 | <img src="https://gist.githubusercontent.com/Potherca/139c4ba16cad5961d3468b8e3db261de/raw/pdsinterop-logo-monochrome.svg" width="128" /> |
| 256x256 | <img src="https://gist.githubusercontent.com/Potherca/139c4ba16cad5961d3468b8e3db261de/raw/pdsinterop-logo-monochrome.svg" width="256" /> |
| 512x512 | <img src="https://gist.githubusercontent.com/Potherca/139c4ba16cad5961d3468b8e3db261de/raw/pdsinterop-logo-monochrome.svg" width="512" /> |
| 1024x1024 | <img src="https://gist.githubusercontent.com/Potherca/139c4ba16cad5961d3468b8e3db261de/raw/pdsinterop-logo-monochrome.svg" width="1024" /> |

**Comment by michielbdejong** [comment]
Cool! Can you put this together with https://github.com/pdsinterop/project-admin/issues/13 to change https://pdsinterop.org/ to something we can point outsiders to?

**Comment by Potherca** [comment]
@michielbdejong Yes, I'll be opening several MRs this week for this log, the CSS en (hopefully) a Jekyll theme to make pdsinterop.org look pretty.

**Comment by Potherca** [comment]
Closing this issue as the logo images have been added to https://github.com/pdsinterop/pdsinterop.github.io/tree/master/logo and can be seen at https://pdsinterop.org/logo/
