### ISSUE TITLE
test app nextcloud stap 1

### ISSUE THREAD

**Issue by poef** [pdsinterop/project-admin#15]
- .wellknown url
- profiel pagina met rdf info/turtle
- bewerkbaar vanuit nextcloud

**Comment by michielbdejong** [comment]
Can you create a Dockerfile that exposes https://[any-host-name]/.well-known/openid-configuration on port 443? Then I can include it into https://github.com/pdsinterop/test-suites/tree/master/servers

**Comment by michielbdejong** [comment]
you can use a self-signed cert, see https://github.com/pdsinterop/test-suites/blob/master/servers/solid-app-kit/Dockerfile#L18-L21 for an example

**Comment by michielbdejong** [comment]
I think we can close this
