### ISSUE TITLE
make team memberships public

### ISSUE THREAD

**Issue by michielbdejong** [pdsinterop/project-admin#7]
See https://github.com/orgs/pdsinterop/people

**Comment by poef** [comment]
I think I've changed it to visible, please confirm :)

**Comment by ylebre** [comment]
Nop, you should be able to change the setting here: https://github.com/orgs/pdsinterop/people

**Comment by Potherca** [comment]
@poef This
![image](https://user-images.githubusercontent.com/195757/84768598-cae2a500-afd4-11ea-8fa9-9663903cfa7a.png)

should be "public". (and yes, this is very confusing and one of Github's more weird UI choices).

**Comment by poef** [comment]
done...
